In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
data = np.array([ [7.6, 6.6, 2.8], [4.9, 0.4, -1.2], [8.0, 2.5, 0.9], [1.4, 1.2, 4.1]])

In [3]:
l = 4
x_sum = 0
y_sum = 0
z_sum = 0

for i in range(4):
    x_sum += data[i][0]
    y_sum += data[i][1]
    y_sum += data[i][2]

In [5]:
x_ave = x_sum / l
y_ave = y_sum / l
z_ave = z_sum / l

In [6]:
arr = []

for i in range(4):
    temp = []
    x = data[i][0] - x_ave
    y = data[i][1] - y_ave
    z = data[i][2] - z_ave
    temp.append(x)
    temp.append(y)
    temp.append(z)
    
    arr.append(temp)
    
d = np.array(arr)    

In [7]:
c = np.dot(np.dot(d.transpose(), d), 1/(l - 1))

In [8]:
print(c)

[[ 9.27583333  5.0725     -2.59833333]
 [ 5.0725     11.22583333 -1.125     ]
 [-2.59833333 -1.125       8.96666667]]


In [9]:
w, v = LA.eig(c)
print(w)

[16.30130041  4.64210064  8.52493228]
