In [68]:
import numpy as np
from numpy import linalg as LA

In [69]:
m = np.array([
[4.39, 1.59, 4.54],
[3.82, 1.82, 3.99] ,
[7.66, 2.95, 7.29 ],
[7.95, 2.55, 7.22 ],
[1.87, 0.68, 2.50 ],
[4.90, 1.97, 5.38 ],
[4.46, 2.30, 5.07 ],
[6.46, 2.28, 5.65 ],
[7.09, 2.71, 6.41 ],
[7.55 ,2.49, 6.52 ]
 ])

In [70]:
sum_x = 0
sum_y = 0
sum_z = 0

for i in range(10):
    sum_x += m[i][0]
    sum_y += m[i][1]
    sum_z += m[i][2]

In [71]:
ave_x = sum_x / 10
ave_y = sum_y / 10
ave_z = sum_z / 10

In [72]:
arr = []

for i in range(10):
    temp = []
    x = m[i][0] - ave_x
    y = m[i][1] - ave_y
    z = m[i][2] - ave_z
    temp.append(x)
    temp.append(y)
    temp.append(z)
    
    arr.append(temp)
    
        
d = np.array(arr)

In [73]:
c = np.dot(np.dot(d.transpose(), d), 1/9)

In [76]:
w, v = LA.eig(c)

In [77]:
print(w)

[6.67430999 0.09048126 0.03286431]


In [78]:
print(v)

[[-0.78028542 -0.57718529 -0.24085639]
 [-0.23780562  0.62998983 -0.73929784]
 [-0.57844891  0.51958632  0.62882979]]
